### ISSUE TITLE
Does not open in Libreoffice (gtk3)

### ISSUE THREAD

**Issue by samdroid-apps** [p-e-w/plotinus#7]
Tested in LibreOffice Writer 5.2.3.1 20(Build:1).  The first issue is that the keyboard shortcut conflicts with the superscript shortcut.  That can be disabled in the libreoffice customize window.

After restarting libreoffice, the superscript shortcut is disabled.  However, pressing <kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>P</kbd> does not open Plotinus.  Nothing is outputted to the console from LibreOffice.

I'll have a look into this, because Poltinus looks awesome, and libreoffice has too many menus :)

**Comment by samdroid-apps** [comment]
Ok, I seem to understand it a little more now.  Plotinus needs a Gtk.Application.  I added a debug statement in Plotnius.Plotnius.new, and it gets logged in normal applications.  But not in libreoffice.  Therefore libreoffice doesn't have a Gtk.Application?

**Comment by p-e-w** [comment]
Yeah, not quite sure what to do here. The problem is that Plotinus needs to register a global shortcut within the host application. I do not know of any reliable way to do that other than using a GtkApplication.

Besides that, everything is already in place, and LibreOffice has been using native GTK menus for a year or so. Therefore, if the shortcut problem were solved, the menu entries should appear immediately.

**Comment by vhaarr** [comment]
https://bugs.documentfoundation.org/show_bug.cgi?id=105457

**Comment by vhaarr** [comment]
Excellent, it works perfectly for libreoffice, thank you!

**Comment by hotice** [comment]
What exactly did you do to get this to work? It doesn't work for me with the latest Plotinus from Git and LibreOffice 5.3.0 or 5.2.2 in Ubuntu 16.10 (with GTK 3.20.9). I did unset the superscript shortcut, but I still get nothing. Any tips?

**Comment by bartlibert** [comment]
For me it was working and then suddenly not anymore, and for me it is
related to the menubar being visible or not. Could you check if this is
also the issue in your case?

Op di 14 feb. 2017 om 14:45 schreef Andrew <notifications@github.com>:

**Comment by hotice** [comment]
Thanks! I'm not sure how to hide the LibreOffice menu as I don't see any option for this, but I did try it in both Ubuntu with Unity (which displays the menu in the top panel, and not in the LibreOffice main window) and Xfce (with the menu in the LibreOffice window), both with the same result.

**Comment by rezzafr33** [comment]
There is .uno:Menubar command that toggle menubar visibility, you can assign it to keyboard shortcut or button.

**Comment by entrity** [comment]
I just built Plotinus from source, and it's not working for me in Libreoffice. Can anyone offer clarification on @bartlibert's comment? I've found no way to hide the menu bar. (I'm running Arch Linux.)

**Comment by bartlibert** [comment]
@entrity if you use a recent version of libreoffice, you can hide the menubar if you use the "notebookbar" style of toolbars.
